const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs');
fs.mkdirSync('screenshots',{recursive:true});
const url=process.env.SITE_URL||'http://127.0.0.1:8768/',approved=JSON.parse(fs.readFileSync('test/fixtures/website-tree-story.json','utf8'));
const executablePath=process.env.HOME+'/Library/Caches/ms-playwright/chromium_headless_shell-1208/chrome-headless-shell-mac-arm64/chrome-headless-shell';
(async()=>{
 const browser=await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:fs.existsSync(executablePath)?{executablePath}:{}),results=[];
 for(const width of [1440,768,375,320]){
  const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url,{waitUntil:"networkidle"});await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(180);
  const storyText=()=>Array.from(document.querySelectorAll('main h2, main p')).map(e=>e.textContent.replace(/\s+/g,' ').trim());
  assert.deepEqual(await page.evaluate(storyText),approved.paragraphs.map(p=>p.text),'All approved story text and its order preserved');
  assert.equal(await page.locator('h1').textContent(),approved.hero.title);
  assert.equal(await page.locator('.scene-tagline').textContent(),approved.hero.subtitle);
  assert.equal(await page.locator('.header-tagline').textContent(),approved.hero.subtitle);
  assert.equal(await page.locator('.company-description strong, .company-description b').count(),0);
  assert.deepEqual(await page.locator('.company-description').evaluate(e=>{const s=getComputedStyle(e);return [s.fontWeight,s.fontSize,s.fontFamily]}),['400','15px','Lato, Arial, sans-serif']);
  assert.equal(await page.locator('body').innerText().then(t=>t.includes('\u2014')),false,'No em dashes');
  for(const link of approved.paragraphs.flatMap(p=>p.links)) assert.equal(await page.locator('#contact a').filter({hasText:link.text}).getAttribute('href'),link.url);
  assert.equal(await page.locator('.scene-contact').getAttribute('href'),'mailto:contact@comprehensionlabs.co');
  const track=page.locator('.scroll-track'),canvas=page.locator('canvas'),shell=page.locator('.site-shell');
  const span=await track.evaluate(e=>e.offsetHeight-innerHeight);assert.equal(span,900);
  assert.equal(await page.locator('.scroll-track button, iframe, video').count(),0);
  assert.equal(await page.locator('main').count(),1,'One actual website');
  assert.equal(await page.getByText('Comprehension Labs',{exact:true}).count(),1,'One shared company title, without an overlapping intro copy');
  const go=async p=>{await page.evaluate(()=>new Promise(resolve=>{let last=scrollY,stable=0;const settle=()=>{stable=scrollY===last?stable+1:0;last=scrollY;if(stable>=3)resolve();else requestAnimationFrame(settle);};requestAnimationFrame(settle);}));await page.evaluate(y=>scrollTo({top:y,behavior:'instant'}),p*span);const position=await page.evaluate(y=>({actual:scrollY,expected:Math.min(y,document.documentElement.scrollHeight-innerHeight)}),p*span);assert(Math.abs(position.actual-position.expected)<=1,`Requested scroll reached within one CSS pixel: ${JSON.stringify(position)}`);await page.waitForFunction(()=>{const t=document.querySelector('.scroll-track');return Math.abs(Number(t.dataset.progress)-Math.min(1,scrollY/Number(t.dataset.span)))<.001;});};
  await go(0);await page.screenshot({path:`screenshots/story-hero-${width}.png`});const openingBrand=await page.locator('.brand').boundingBox();assert(openingBrand.y>450&&openingBrand.y+openingBrand.height<900,'Shared header starts beneath the tree');assert(Math.abs(openingBrand.x+openingBrand.width/2-await page.evaluate(()=>document.documentElement.clientWidth/2))<1,'Hero title remains centered');assert(Math.abs((await page.locator('.scene-identity').boundingBox()).y-openingBrand.y-openingBrand.height-12)<1,'Hero subtitle retains its 12px gap');const first=await canvas.evaluate(c=>c.toDataURL());await page.waitForTimeout(250);assert.equal(await canvas.evaluate(c=>c.toDataURL()),first,'No time loop');
  await go(.2);assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),first,'Scroll changes the particle sculpture');assert(Number(await canvas.getAttribute('data-scroll-displacement'))>20,'Individual atoms move relative to the tree, beyond its global lift and rotation');await page.waitForTimeout(120);const partial=await canvas.evaluate(c=>c.toDataURL());
  await go(.4);assert.equal(await shell.evaluate(e=>e.inert),false);assert(Number(await shell.evaluate(e=>getComputedStyle(e).opacity))>.8);assert.deepEqual(await shell.evaluate(e=>{const s=getComputedStyle(e);return [s.transform,s.clipPath,s.boxShadow]}),['none','none','none'],'Original site enters directly, with no manuscript or card transform');
  const movingBrand=await page.locator('.brand').boundingBox();assert(movingBrand.y<openingBrand.y&&movingBrand.width<=openingBrand.width+.01,'The same title moves into the centered header without growing');assert.equal(await page.locator('.brand').evaluate(e=>getComputedStyle(e).opacity),'1','Shared title never fades out');
  await go(.65);assert(Number(await track.getAttribute('data-reveal'))>.7);await page.screenshot({path:`screenshots/direct-content-${width}.png`});
  assert.equal(await page.locator('.brand').evaluate(e=>getComputedStyle(e).transform),'none','Title merges into its original natural header position');assert.equal(await page.locator('.header-tagline').evaluate(e=>getComputedStyle(e).opacity),'1','Approved subtitle remains below the title after transition');
  await go(.2);await page.waitForTimeout(120);assert.equal(await canvas.evaluate(c=>c.toDataURL()),partial,'Exact reverse at same scroll position');
  await go(0);const restingTree=await canvas.evaluate(c=>c.toDataURL()),b=await canvas.boundingBox();await page.mouse.move(b.x+b.width*.5,b.y+b.height*.6);await page.waitForTimeout(400);assert(Number(await canvas.getAttribute('data-displacement'))>15);assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),restingTree,'Pointer visibly moves the knowledge-tree particles');await page.mouse.move(0,0);await page.waitForTimeout(700);
  await go(.7);await page.waitForTimeout(250);const plainPage=await canvas.evaluate(c=>c.toDataURL());await page.mouse.move(120,80,{steps:10});await page.waitForTimeout(100);assert.equal(await canvas.evaluate(c=>c.toDataURL()),plainPage,'No cursor trail remains after the tree fades');
  await go(1);assert.equal(await shell.evaluate(e=>e.inert),false);assert.equal(await shell.evaluate(e=>getComputedStyle(e).opacity),'1');
  const boundary=[];for(const y of [span-1,span,span+1]){await page.evaluate(y=>scrollTo({top:y,behavior:'instant'}),y);await page.waitForTimeout(180);boundary.push(await shell.evaluate(e=>e.getBoundingClientRect().top));}assert(Math.abs(boundary[0]-1)<1&&Math.abs(boundary[1])<1&&Math.abs(boundary[2]+1)<1,'Continuous natural page scroll across the intro boundary');
  await page.screenshot({path:`screenshots/website-${width}.png`});
  for(const id of ['data','research','approach','contact']){await page.locator(`nav a[href="/${id}"]`).click();assert.equal(new URL(page.url()).pathname,'/'+id);assert.equal(new URL(page.url()).hash,'');await page.waitForFunction(id=>{const r=document.getElementById(id).getBoundingClientRect();return r.top<innerHeight&&r.bottom>0;},id,{timeout:4000});await page.waitForTimeout(150);}
  await page.locator('.theme-toggle').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');await page.locator('.theme-toggle').click();
  await page.addScriptTag({path:require.resolve('axe-core')});const axe=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));assert.deepEqual(axe.violations.map(v=>v.id),[]);
  if(width===1440){await go(1.8);await page.setViewportSize({width:1439,height:900});await page.waitForTimeout(150);await go(0);const restored=await page.locator('.brand').boundingBox();assert(restored.y>450&&restored.y+restored.height<900,'Header returns correctly after resizing below the intro');await page.setViewportSize({width,height:900});await page.waitForTimeout(150);}
  await go(.4);const grayscale=await canvas.evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;for(let i=0;i<d.length;i+=148)if(d[i+3]&&Math.max(d[i],d[i+1],d[i+2])-Math.min(d[i],d[i+1],d[i+2])>1)return false;return true});assert(grayscale,'Monochrome canvas');
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(200);assert.equal(await track.evaluate(e=>e.offsetHeight),0);assert.equal(await shell.evaluate(e=>getComputedStyle(e).opacity),'1');assert(await page.locator('#story').evaluate(e=>e.getBoundingClientRect().top<innerHeight));
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);results.push({width,scrollTrack:'200vh',copyPreserved:true,heroAndBodyTypography:true,noCursorTrail:true,scrollReversible:true,releaseBoundary:boundary,monochrome:true,hover:true,navigation:true,reducedMotion:true,axeViolations:0,errors});await page.close();
 }
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await page.goto(url,{waitUntil:"networkidle"});await page.waitForTimeout(200);const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:195,y:650}]});for(let i=1;i<=10;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:195,y:650-i*35}]});await page.waitForTimeout(20)}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(300);assert(await page.evaluate(()=>scrollY>100));await page.setViewportSize({width:844,height:390});await page.waitForTimeout(300);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('.scroll-track').evaluate(e=>e.offsetHeight-innerHeight),390);await page.close();
 const keyboard=await browser.newPage();await keyboard.goto(url,{waitUntil:"networkidle"});await keyboard.keyboard.press('Tab');assert.equal(await keyboard.evaluate(()=>document.activeElement.textContent),'Skip animation');await keyboard.keyboard.press('Enter');await keyboard.waitForTimeout(200);assert(await keyboard.locator('#story').evaluate(e=>e.getBoundingClientRect().top<innerHeight));await keyboard.close();
 for(const width of [1440,320]){
  const nojs=await browser.newPage({javaScriptEnabled:false,viewport:{width,height:900}});await nojs.goto(url,{waitUntil:'networkidle'});
  assert.equal(await nojs.locator('main section').count(),5);assert(await nojs.locator('#story').isVisible());
  assert.deepEqual(await nojs.locator('main h2, main p').allTextContents(),approved.paragraphs.map(p=>p.text),'No-JavaScript fallback has all approved copy');
  assert.equal(await nojs.locator('h1').textContent(),approved.hero.title);assert.equal(await nojs.locator('.header-tagline').textContent(),approved.hero.subtitle);
  assert.equal(await nojs.locator('#contact a').first().getAttribute('href'),'mailto:contact@comprehensionlabs.co');
  assert.equal(await nojs.locator('#contact a').last().getAttribute('href'),'https://cal.com/riaan-kumar-laogqu');
  assert(await nojs.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await nojs.close();
 }
 await browser.close();fs.writeFileSync('test-results.json',JSON.stringify({results,touchScroll:true,orientationResize:true,keyboardSkip:true,noJSFullContent:true},null,2));console.log('PASS',JSON.stringify(results));
})().catch(e=>{console.error(e);process.exit(1)});
