const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs');
fs.mkdirSync('screenshots',{recursive:true});
const url=process.env.SITE_URL||'http://127.0.0.1:8768/',original=fs.readFileSync('test/fixtures/original.html','utf8');
const executablePath=process.env.HOME+'/Library/Caches/ms-playwright/chromium_headless_shell-1208/chrome-headless-shell-mac-arm64/chrome-headless-shell';
(async()=>{
 const browser=await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:fs.existsSync(executablePath)?{executablePath}:{}),results=[];
 for(const width of [1440,768,375,320]){
  const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url,{waitUntil:"networkidle"});await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(180);
  // Compare computed typography against the original page at this exact viewport.
  const baseline=await browser.newPage({viewport:{width,height:900}});await baseline.setContent(original);await baseline.evaluate(()=>document.fonts.ready);
  const typography=()=>Array.from((document.querySelector('.site-shell')||document).querySelectorAll('main h1, main h2, main p, main li, nav a')).map(e=>{const st=getComputedStyle(e);const originalHeadline=e.matches('main h1');return {text:e.textContent.replace(/\s+/g,' ').trim(),style:Object.fromEntries(['fontFamily','fontSize','fontWeight','lineHeight','letterSpacing','fontStyle'].filter(k=>!originalHeadline||k!=='fontSize').map(k=>[k,originalHeadline&&['lineHeight','letterSpacing'].includes(k)?(parseFloat(st[k])/parseFloat(st.fontSize)).toFixed(4):st[k]]))}}).sort((a,b)=>a.text.localeCompare(b.text));
  assert.deepEqual(await page.evaluate(typography),await baseline.evaluate(typography),'Original body/navigation wording and typography preserved; brand typography and main tagline size intentionally updated');await baseline.close();
  const track=page.locator('.scroll-track'),canvas=page.locator('canvas'),shell=page.locator('.site-shell');
  const span=await track.evaluate(e=>e.offsetHeight-innerHeight);assert.equal(span,900);
  assert.equal(await page.locator('.scroll-track button, iframe, video').count(),0);
  assert.equal(await page.locator('main').count(),1,'One actual website');
  assert.equal(await page.getByText('Comprehension Labs',{exact:true}).count(),1,'One shared company title, without an overlapping intro copy');
  const unchanged=await page.evaluate(original=>{const source=new DOMParser().parseFromString(original,'text/html');const texts=root=>Array.from(root.querySelectorAll('main h1, main h2, main p, main li')).map(x=>x.textContent.replace(/\s+/g,' ').trim()).sort();return JSON.stringify(texts(source))===JSON.stringify(texts(document));},original);assert(unchanged,'All original main text preserved');
  const go=async p=>{await page.evaluate(y=>scrollTo({top:y,behavior:'instant'}),p*span);try { await page.waitForFunction(p=>Math.abs(Number(document.querySelector('.scroll-track').dataset.progress)-Math.min(1,p))<.001,p); } catch(error) { console.error('Scroll check failed', {width,requested:p,state:await page.evaluate(()=>({scroll:scrollY,track:{...document.querySelector('.scroll-track').dataset},hidden:document.hidden,height:innerHeight,active:document.activeElement.tagName,hash:location.hash}))}); throw error; }};
  await go(0);const openingBrand=await page.locator('.brand').boundingBox();assert(openingBrand.y>450&&openingBrand.y+openingBrand.height<900,'Shared header starts beneath the tree');const first=await canvas.evaluate(c=>c.toDataURL());await page.waitForTimeout(250);assert.equal(await canvas.evaluate(c=>c.toDataURL()),first,'No time loop');
  await go(.2);assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),first,'Scroll changes the particle sculpture');assert(Number(await canvas.getAttribute('data-scroll-displacement'))>20,'Individual atoms move relative to the tree, beyond its global lift and rotation');await page.waitForTimeout(120);const partial=await canvas.evaluate(c=>c.toDataURL());
  await go(.4);assert.equal(await shell.evaluate(e=>e.inert),false);assert(Number(await shell.evaluate(e=>getComputedStyle(e).opacity))>.8);assert.deepEqual(await shell.evaluate(e=>{const s=getComputedStyle(e);return [s.transform,s.clipPath,s.boxShadow]}),['none','none','none'],'Original site enters directly, with no manuscript or card transform');
  const movingBrand=await page.locator('.brand').boundingBox();assert(movingBrand.y<openingBrand.y&&movingBrand.width<=openingBrand.width+.01,'The same title moves into the centered header without growing');assert.equal(await page.locator('.brand').evaluate(e=>getComputedStyle(e).opacity),'1','Shared title never fades out');
  await go(.65);assert(Number(await track.getAttribute('data-reveal'))>.7);await page.screenshot({path:`screenshots/direct-content-${width}.png`});
  assert.equal(await page.locator('.brand').evaluate(e=>getComputedStyle(e).transform),'none','Title merges into its original natural header position');
  await go(.2);await page.waitForTimeout(120);assert.equal(await canvas.evaluate(c=>c.toDataURL()),partial,'Exact reverse at same scroll position');
  await go(0);const restingTree=await canvas.evaluate(c=>c.toDataURL()),b=await canvas.boundingBox();await page.mouse.move(b.x+b.width*.5,b.y+b.height*.6);await page.waitForTimeout(400);assert(Number(await canvas.getAttribute('data-displacement'))>15);assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),restingTree,'Pointer visibly moves the knowledge-tree particles');await page.mouse.move(0,0);await page.waitForTimeout(700);
  await go(.7);await page.waitForTimeout(250);const plainPage=await canvas.evaluate(c=>c.toDataURL());await page.mouse.move(120,80,{steps:10});await page.waitForTimeout(100);assert.equal(await canvas.evaluate(c=>c.toDataURL()),plainPage,'No cursor trail remains after the tree fades');
  await go(1);assert.equal(await shell.evaluate(e=>e.inert),false);assert.equal(await shell.evaluate(e=>getComputedStyle(e).opacity),'1');
  const boundary=[];for(const y of [span-1,span,span+1]){await page.evaluate(y=>scrollTo({top:y,behavior:'instant'}),y);await page.waitForTimeout(180);boundary.push(await shell.evaluate(e=>e.getBoundingClientRect().top));}assert(Math.abs(boundary[0]-1)<1&&Math.abs(boundary[1])<1&&Math.abs(boundary[2]+1)<1,'Continuous natural page scroll across the intro boundary');
  await page.screenshot({path:`screenshots/website-${width}.png`});
  for(const id of ['data','research','approach','contact']){await page.locator(`nav a[href="/${id}"]`).click();assert.equal(new URL(page.url()).pathname,'/'+id);assert.equal(new URL(page.url()).hash,'');await page.waitForFunction(id=>{const r=document.getElementById(id).getBoundingClientRect();return r.top<innerHeight&&r.bottom>0;},id,{timeout:4000});await page.waitForTimeout(150);}
  await page.locator('.theme-toggle').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');await page.locator('.theme-toggle').click();
  await page.addScriptTag({path:require.resolve('axe-core')});const axe=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));assert.deepEqual(axe.violations.map(v=>v.id),[]);
  if(width===1440){await go(1.8);await page.setViewportSize({width:1439,height:900});await page.waitForTimeout(150);await go(0);const restored=await page.locator('.brand').boundingBox();assert(restored.y>450&&restored.y+restored.height<900,'Header returns correctly after resizing below the intro');await page.setViewportSize({width,height:900});await page.waitForTimeout(150);}
  await go(.4);const grayscale=await canvas.evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;for(let i=0;i<d.length;i+=148)if(d[i+3]&&Math.max(d[i],d[i+1],d[i+2])-Math.min(d[i],d[i+1],d[i+2])>1)return false;return true});assert(grayscale,'Monochrome canvas');
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(200);assert.equal(await track.evaluate(e=>e.offsetHeight),0);assert.equal(await shell.evaluate(e=>getComputedStyle(e).opacity),'1');assert(await page.locator('#research').evaluate(e=>e.getBoundingClientRect().top<innerHeight));
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);results.push({width,scrollTrack:'200vh',copyPreserved:true,typographyPreserved:true,noCursorTrail:true,scrollReversible:true,releaseBoundary:boundary,monochrome:true,hover:true,navigation:true,reducedMotion:true,axeViolations:0,errors});await page.close();
 }
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await page.goto(url,{waitUntil:"networkidle"});await page.waitForTimeout(200);const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:195,y:650}]});for(let i=1;i<=10;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:195,y:650-i*35}]});await page.waitForTimeout(20)}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(300);assert(await page.evaluate(()=>scrollY>100));await page.setViewportSize({width:844,height:390});await page.waitForTimeout(300);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('.scroll-track').evaluate(e=>e.offsetHeight-innerHeight),390);await page.close();
 const keyboard=await browser.newPage();await keyboard.goto(url,{waitUntil:"networkidle"});await keyboard.keyboard.press('Tab');assert.equal(await keyboard.evaluate(()=>document.activeElement.textContent),'Skip animation');await keyboard.keyboard.press('Enter');await keyboard.waitForTimeout(200);assert(await keyboard.locator('#research').evaluate(e=>e.getBoundingClientRect().top<innerHeight));await keyboard.close();
 const nojs=await browser.newPage({javaScriptEnabled:false});await nojs.goto(url,{waitUntil:"networkidle"});assert.equal(await nojs.locator('main section').count(),6);assert(await nojs.locator('#research').isVisible());assert.equal(await nojs.locator('#contact a').getAttribute('href'),'mailto:founders@comprehensionlabs.com');await nojs.close();
 await browser.close();fs.writeFileSync('test-results.json',JSON.stringify({results,touchScroll:true,orientationResize:true,keyboardSkip:true,noJSFullContent:true},null,2));console.log('PASS',JSON.stringify(results));
})().catch(e=>{console.error(e);process.exit(1)});
